.TH FUSECOMPRESS_OFFLINE 1 "2008-06-06" "1.99.16" "Compressed filesystem offline"
.SH NAME
fusecompress_offline \- decompress or compress data without need to mount the compressed virtual filesystem
.SH SYNOPSIS
.B fusecompress_offline
[\-h] [\-v] [\-o OPTIONS] path
.SH DESCRIPTION

If compression method is set the data will be compressed by required compression method. Files already compressed by a different compression method are recompressed to the required compression method. Files already compressed by the required compression method are left untouched.
If compression method is not set (using -o fc_c) then file(s) are decompressed.

Path may be directory or file. Directories are processed recursively.

This allows you to, among other things,  "compress" an existing folder (ex:)
$ fusecompress_offline -o fc_c:lzma formerly_uncompressed_folder

and to "decompress" an existing compressed folder (ex:)

$ fusecompress_offline compressed_folder

.SH OPTIONS
.TP
.B \-h, \-\-help
Prints help.
.TP
.B \-v, \-\-version
Prints version.
.TP
.B \-o, \-\-options

.B fc_c:arg
set compression method (lzo/bzip2/zlib/lzma) (default:zlib)

.B fc_b:arg
set size of the blocks in kilobytes (default:100)

.B fc_d
run in debug mode

.B fc_ma:"arg1;arg2"
files with passed mime types to be always not compressed

.B fc_mr:"arg1;arg2"
files with passed mime types to be always compressed

Lzo is the fastest, bzip2 has high compression ratio, but it is the slowest, zlib is somewhere between them in terms of speed and compression ratio and lzma has highest compression ratio, it's compression speed is better than bzip2 and decompression is fast.

Block size influences compression ratio. Bigger block size allows better compression ratio, but random access to data will be slower and memory requirements will be bigger.

.SH DISCLAIMER
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer to the "COPYING" file distributed with fusecompress for complete details.
.SH AUTHORS
fusecompress_offline was written by Milan Svoboda <milan.svoboda@centrum.cz>.
.SH "SEE ALSO"
fusecompress
