.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH FUSECOMPRESS 1 "2008-06-06" "1.99.16" "Compressed filesystem"
.SH NAME
fusecompress \- mounts an compressed virtual filesystem
.SH SYNOPSIS
.B fusecompress [OPTION]... rootDir mountPoint
.SH DESCRIPTION
FuseCompress creates a virtual compressed filesystem which stores compressed data in the rootDir directory and makes the uncompressed data visible at the mountPoint directory.

Compression type (or uncompressed state) of files in the rootDir is not changed during work. Use fusecompress_offline if you want to decompress file(s) or change compression type of the file(s).

.B Examples:

Storage directory is /tmp/fc and mount point is /mnt/fc in all following examples.

	o Mount directory

		fusecompress /tmp/fc /mnt/fc

	o Unmount directory

		fusermount \-u /mnt/fc

.B Tips and tricks:

	How to obtain compression ratio?

	o	Run this command in the mountPoint directory when mounted with FuseCompress:

.Vb 2
			du \-sh
			du \-sh \-\-apparent-size
.Ve

.B File and magic utilities:

Put this config into ~/.magic or /etc/magic file to allow file utility recognize FuseCompress file format:

.Vb 8
\&	0       string  \\037\\135\\211    FuseCompress(ed) data
.Ve

.SH OPTIONS
.TP
.B \-h, \-\-help
Prints help.
.TP
.B \-v, \-\-version
Prints version.
.TP
.B \-o, \-\-options

.B fc_c:arg
set compression method (lzo/bzip2/zlib/lzma/none) (default:zlib)

.B fc_b:arg
set size of the blocks in kilobytes (default:100)

.B fc_d
run in debug mode

.B fc_ma:"arg1;arg2"
files with passed mime types to be always not compressed

.B fc_mr:"arg1;arg2"
files with passed mime types to be always compressed

Other options are passed directly to the fuse library. See fuse documentation for full list of supported options.

Useful parameters for fuse library:

Fuse library must be configured to support this features - configuration file /etc/fuse.conf must contains at least this option: user_allow_other.

.B allow_other

This option overrides the security measure restricting file access to the user mounting the filesystem. So all users (including root) can access the files. This option is by default only allowed to root, but this restriction can be removed with a configuration option described in the previous section.

.B allow_root

This option is similar to 'allow_other' but file access is limited to the user mounting the filesystem and root. This option and 'allow_other' are mutually exclusive.

.B nonempty

This option allows you to use the same directory for rootDir and mountPoint.
 
Lzo is the fastest, bzip2 has high compression ratio, but it is the slowest, zlib is somewhere between them in terms of speed and compression ratio and lzma has highest compression ratio, it's compression speed is better than bzip2 and decompression is fast. The none compression method is there for testing only as it doesn't compress data, it copies the data without any modification (fusecompress' header is added).

Block size influences compression ratio. Bigger block size allows better compression ratio, but random access to data will be slower and memory requirements will be bigger.

.SH DISCLAIMER
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Please refer to the "COPYING" file distributed with fusecompress for complete details.
.SH AUTHORS
fusecompress was written by Milan Svoboda <milan.svoboda@centrum.cz>.
.SH "SEE ALSO"
fusecompress_offline
